[2021-07-27 12:05:49,019][WARNING][1363]: start backup threading
[2021-07-27 12:05:49,025][WARNING][1363]: start backup threading
[2021-07-27 12:05:49,026][INFO][1363]: success to start polaris engine
[2021-07-27 12:05:49,034][WARNING][1363]: start timing update job
[2021-07-27 12:05:49,036][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Production', 'service': '1961537:212729856', 'is_internal_request': False}
[2021-07-27 12:05:49,039][WARNING][1363]: start circuit break job
[2021-07-27 12:05:49,046][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:05:49,049][WARNING][1363]: start od job
[2021-07-27 12:05:49,052][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:49,056][WARNING][1363]: start job of client reporting
[2021-07-27 12:05:50,063][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:50,051][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:50,052][ERROR][1363]: receive exception when add client report task Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 26, in tcp_round_trip
    rsp = await asyncio.wait_for(options.checker.read_frame(conn), get_remain_time(ctx.deadline))
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 139, in report_client
    report_rsp = await proxy.report_client(req_proto, ctx, opts)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpcapi_pb2_trpc.py", line 41, in report_client
    return await self.client.invoke(ctx, request, rsp_cls, options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 287, in invoke
    raise err
  File "/usr/local/lib/python3.6/dist-packages/trpc/filter.py", line 97, in handle
    rsp = await asyncio.wait_for(func(ctx, req_obj), wait_for_time)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 325, in func
    rsp_buff = await client_ts.round_trip(ctx, req_buff, opts.call_options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 32, in tcp_round_trip
    "client reached deadline to %s, %s io error " % (options.address, repr(e)))
trpc.exceptions.ClientTimeoutError: client reached deadline to ('9.136.124.80', 8091), TimeoutError() io error . timeout reason: ClientTimeoutReason.DownstreamTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 643, in add_client_report_task
    await self.do_period_client_report(values)
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 669, in do_period_client_report
    report_client_resp = await self.svc_connector.report_client(report_client_req)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 141, in report_client
    raise SDKError(ErrorCode.ErrCodeNetworkError, "fail to call report_client %s" % repr(e))
polaris.pkg.model.error.SDKError: (1007, 'fail to call report_client ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')

[2021-07-27 12:05:51,065][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:51,069][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:52,079][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:52,086][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:53,095][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:53,102][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:54,114][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:54,121][ERROR][1363]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:54,127][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:05:54,133][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:55,142][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:55,151][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:56,158][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:56,164][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:57,174][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:57,181][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:58,190][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:58,196][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:59,054][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:05:59,208][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:59,215][ERROR][1363]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:05:59,216][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:05:59,220][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:00,227][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:00,233][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:01,246][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:01,253][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:02,263][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:02,270][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:03,280][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:03,287][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:04,295][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:04,320][ERROR][1363]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:04,321][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:04,325][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:05,333][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:05,337][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:06,348][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:06,353][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:07,365][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:07,371][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:08,379][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:08,386][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:09,393][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:09,398][ERROR][1363]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:09,398][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:09,402][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:10,407][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:10,411][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:11,418][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:11,423][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:12,432][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:12,438][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:13,445][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:13,452][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:14,459][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:14,465][ERROR][1363]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:14,467][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:14,471][INFO][1363]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:15,480][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:15,486][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:16,495][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:16,500][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:17,507][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:17,513][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:18,524][ERROR][1363]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:18,529][WARNING][1363]: cannot find naming of polaris
[2021-07-27 12:06:25,653][WARNING][1375]: start backup threading
[2021-07-27 12:06:25,656][WARNING][1375]: start backup threading
[2021-07-27 12:06:25,656][INFO][1375]: success to start polaris engine
[2021-07-27 12:06:25,666][WARNING][1375]: start timing update job
[2021-07-27 12:06:25,667][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Production', 'service': '1961537:212729856', 'is_internal_request': False}
[2021-07-27 12:06:25,670][WARNING][1375]: start circuit break job
[2021-07-27 12:06:25,674][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:25,677][WARNING][1375]: start od job
[2021-07-27 12:06:25,682][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:25,684][WARNING][1375]: start job of client reporting
[2021-07-27 12:06:26,691][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:26,699][ERROR][1375]: receive exception when add client report task Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 26, in tcp_round_trip
    rsp = await asyncio.wait_for(options.checker.read_frame(conn), get_remain_time(ctx.deadline))
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 139, in report_client
    report_rsp = await proxy.report_client(req_proto, ctx, opts)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpcapi_pb2_trpc.py", line 41, in report_client
    return await self.client.invoke(ctx, request, rsp_cls, options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 287, in invoke
    raise err
  File "/usr/local/lib/python3.6/dist-packages/trpc/filter.py", line 97, in handle
    rsp = await asyncio.wait_for(func(ctx, req_obj), wait_for_time)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 325, in func
    rsp_buff = await client_ts.round_trip(ctx, req_buff, opts.call_options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 32, in tcp_round_trip
    "client reached deadline to %s, %s io error " % (options.address, repr(e)))
trpc.exceptions.ClientTimeoutError: client reached deadline to ('9.136.124.80', 8091), TimeoutError() io error . timeout reason: ClientTimeoutReason.DownstreamTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 643, in add_client_report_task
    await self.do_period_client_report(values)
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 669, in do_period_client_report
    report_client_resp = await self.svc_connector.report_client(report_client_req)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 141, in report_client
    raise SDKError(ErrorCode.ErrCodeNetworkError, "fail to call report_client %s" % repr(e))
polaris.pkg.model.error.SDKError: (1007, 'fail to call report_client ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')

[2021-07-27 12:06:26,699][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:27,711][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:27,718][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:28,731][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:28,737][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:29,746][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:29,753][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:30,761][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:30,768][ERROR][1375]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:30,773][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:30,778][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:31,785][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:31,789][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:32,801][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:32,807][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:33,814][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:33,821][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:34,834][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:34,840][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:35,700][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:35,851][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:35,858][ERROR][1375]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:35,859][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:35,862][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:36,869][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:36,873][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:37,883][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:37,889][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:38,898][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:38,907][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:39,917][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:39,923][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:40,935][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:40,942][ERROR][1375]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:40,943][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:40,947][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:41,955][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:41,961][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:42,972][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:42,979][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:43,989][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:43,995][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:45,004][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:45,012][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:46,020][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:46,027][ERROR][1375]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:46,028][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:46,032][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:47,038][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:47,042][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:48,054][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:48,062][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:49,070][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:49,076][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:50,062][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:50,066][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:51,074][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:51,082][ERROR][1375]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:51,083][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:51,087][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:52,098][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:52,104][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:53,112][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:53,116][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:54,124][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:54,127][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:55,134][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:55,140][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:56,150][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:56,158][ERROR][1375]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:56,159][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:56,165][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:06:57,175][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:57,178][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:58,183][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:58,188][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:06:59,197][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:06:59,204][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:00,212][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:00,216][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:01,222][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:01,227][ERROR][1375]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:01,228][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:01,232][INFO][1375]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:07:02,239][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:02,244][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:03,253][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:03,259][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:04,266][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:04,272][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:05,281][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:05,288][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:06,297][ERROR][1375]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:06,305][ERROR][1375]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:06,305][WARNING][1375]: cannot find naming of polaris
[2021-07-27 12:07:54,476][WARNING][1387]: start backup threading
[2021-07-27 12:07:54,478][WARNING][1387]: start backup threading
[2021-07-27 12:07:54,479][INFO][1387]: success to start polaris engine
[2021-07-27 12:07:54,488][INFO][1387]: miss local cache and begin to load remote value for {'namespace': 'Production', 'service': '1961537:212729856', 'is_internal_request': False}
[2021-07-27 12:07:54,488][WARNING][1387]: start timing update job
[2021-07-27 12:07:54,492][INFO][1387]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:07:54,494][WARNING][1387]: start circuit break job
[2021-07-27 12:07:54,499][WARNING][1387]: cannot find naming of polaris
[2021-07-27 12:07:54,502][WARNING][1387]: start od job
[2021-07-27 12:07:54,509][WARNING][1387]: start job of client reporting
[2021-07-27 12:07:55,509][ERROR][1387]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:55,517][ERROR][1387]: receive exception when add client report task Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 26, in tcp_round_trip
    rsp = await asyncio.wait_for(options.checker.read_frame(conn), get_remain_time(ctx.deadline))
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 139, in report_client
    report_rsp = await proxy.report_client(req_proto, ctx, opts)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpcapi_pb2_trpc.py", line 41, in report_client
    return await self.client.invoke(ctx, request, rsp_cls, options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 287, in invoke
    raise err
  File "/usr/local/lib/python3.6/dist-packages/trpc/filter.py", line 97, in handle
    rsp = await asyncio.wait_for(func(ctx, req_obj), wait_for_time)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 325, in func
    rsp_buff = await client_ts.round_trip(ctx, req_buff, opts.call_options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 32, in tcp_round_trip
    "client reached deadline to %s, %s io error " % (options.address, repr(e)))
trpc.exceptions.ClientTimeoutError: client reached deadline to ('9.141.66.121', 8091), TimeoutError() io error . timeout reason: ClientTimeoutReason.DownstreamTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 643, in add_client_report_task
    await self.do_period_client_report(values)
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 669, in do_period_client_report
    report_client_resp = await self.svc_connector.report_client(report_client_req)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 141, in report_client
    raise SDKError(ErrorCode.ErrCodeNetworkError, "fail to call report_client %s" % repr(e))
polaris.pkg.model.error.SDKError: (1007, 'fail to call report_client ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')

[2021-07-27 12:07:55,518][WARNING][1387]: cannot find naming of polaris
[2021-07-27 12:07:56,530][ERROR][1387]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:56,535][WARNING][1387]: cannot find naming of polaris
[2021-07-27 12:07:57,542][ERROR][1387]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:07:57,548][WARNING][1387]: cannot find naming of polaris
[2021-07-27 12:08:04,255][WARNING][1399]: start backup threading
[2021-07-27 12:08:04,258][WARNING][1399]: start backup threading
[2021-07-27 12:08:04,258][INFO][1399]: success to start polaris engine
[2021-07-27 12:08:04,270][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Production', 'service': '1961537:212729856', 'is_internal_request': False}
[2021-07-27 12:08:04,271][WARNING][1399]: start timing update job
[2021-07-27 12:08:04,275][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:04,278][WARNING][1399]: start circuit break job
[2021-07-27 12:08:04,282][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:04,286][WARNING][1399]: start od job
[2021-07-27 12:08:04,294][WARNING][1399]: start job of client reporting
[2021-07-27 12:08:05,298][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:05,305][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:05,332][ERROR][1399]: receive exception when add client report task Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 26, in tcp_round_trip
    rsp = await asyncio.wait_for(options.checker.read_frame(conn), get_remain_time(ctx.deadline))
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 139, in report_client
    report_rsp = await proxy.report_client(req_proto, ctx, opts)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpcapi_pb2_trpc.py", line 41, in report_client
    return await self.client.invoke(ctx, request, rsp_cls, options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 287, in invoke
    raise err
  File "/usr/local/lib/python3.6/dist-packages/trpc/filter.py", line 97, in handle
    rsp = await asyncio.wait_for(func(ctx, req_obj), wait_for_time)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 325, in func
    rsp_buff = await client_ts.round_trip(ctx, req_buff, opts.call_options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 32, in tcp_round_trip
    "client reached deadline to %s, %s io error " % (options.address, repr(e)))
trpc.exceptions.ClientTimeoutError: client reached deadline to ('9.141.66.125', 8091), TimeoutError() io error . timeout reason: ClientTimeoutReason.DownstreamTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 643, in add_client_report_task
    await self.do_period_client_report(values)
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 669, in do_period_client_report
    report_client_resp = await self.svc_connector.report_client(report_client_req)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 141, in report_client
    raise SDKError(ErrorCode.ErrCodeNetworkError, "fail to call report_client %s" % repr(e))
polaris.pkg.model.error.SDKError: (1007, 'fail to call report_client ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')

[2021-07-27 12:08:06,318][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:06,324][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:07,332][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:07,336][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:08,343][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:08,350][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:09,360][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:09,369][ERROR][1399]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:09,374][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:09,379][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:10,387][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:10,394][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:11,407][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:11,414][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:12,422][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:12,428][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:13,442][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:13,448][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:14,334][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:14,460][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:14,466][ERROR][1399]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:14,468][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:14,472][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:15,479][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:15,485][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:16,494][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:16,499][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:17,506][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:17,511][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:18,522][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:18,528][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:19,541][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:19,547][ERROR][1399]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:19,548][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:19,551][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:20,537][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:20,543][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:21,552][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:21,559][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:22,569][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:22,576][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:23,589][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:23,595][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:24,605][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:24,612][ERROR][1399]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:24,613][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:24,618][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:25,626][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:25,633][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:26,642][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:26,649][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:27,657][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:27,663][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:28,674][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:28,681][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:29,689][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:29,700][ERROR][1399]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:29,701][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:29,705][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:30,713][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:30,720][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:31,731][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:31,738][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:32,745][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:32,752][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:33,760][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:33,765][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:34,773][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:34,780][ERROR][1399]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:34,781][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:34,785][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:35,792][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:35,797][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:36,803][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:36,809][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:37,819][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:37,823][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:38,830][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:38,836][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:39,846][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:40,112][ERROR][1399]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:40,113][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:40,117][INFO][1399]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:08:41,123][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:41,129][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:42,139][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:42,146][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:43,156][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:43,164][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:44,177][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:44,185][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:08:45,195][ERROR][1399]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:45,202][ERROR][1399]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:08:45,203][WARNING][1399]: cannot find naming of polaris
[2021-07-27 12:09:13,649][WARNING][1411]: start backup threading
[2021-07-27 12:09:13,652][WARNING][1411]: start backup threading
[2021-07-27 12:09:13,652][INFO][1411]: success to start polaris engine
[2021-07-27 12:09:13,665][WARNING][1411]: start timing update job
[2021-07-27 12:09:13,666][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Production', 'service': '1961537:212729856', 'is_internal_request': False}
[2021-07-27 12:09:13,669][WARNING][1411]: start circuit break job
[2021-07-27 12:09:13,674][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:13,678][WARNING][1411]: start od job
[2021-07-27 12:09:13,683][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:13,686][WARNING][1411]: start job of client reporting
[2021-07-27 12:09:14,695][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:14,700][ERROR][1411]: receive exception when add client report task Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 26, in tcp_round_trip
    rsp = await asyncio.wait_for(options.checker.read_frame(conn), get_remain_time(ctx.deadline))
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 139, in report_client
    report_rsp = await proxy.report_client(req_proto, ctx, opts)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpcapi_pb2_trpc.py", line 41, in report_client
    return await self.client.invoke(ctx, request, rsp_cls, options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 287, in invoke
    raise err
  File "/usr/local/lib/python3.6/dist-packages/trpc/filter.py", line 97, in handle
    rsp = await asyncio.wait_for(func(ctx, req_obj), wait_for_time)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 325, in func
    rsp_buff = await client_ts.round_trip(ctx, req_buff, opts.call_options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 32, in tcp_round_trip
    "client reached deadline to %s, %s io error " % (options.address, repr(e)))
trpc.exceptions.ClientTimeoutError: client reached deadline to ('9.141.66.84', 8091), TimeoutError() io error . timeout reason: ClientTimeoutReason.DownstreamTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 643, in add_client_report_task
    await self.do_period_client_report(values)
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 669, in do_period_client_report
    report_client_resp = await self.svc_connector.report_client(report_client_req)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 141, in report_client
    raise SDKError(ErrorCode.ErrCodeNetworkError, "fail to call report_client %s" % repr(e))
polaris.pkg.model.error.SDKError: (1007, 'fail to call report_client ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')

[2021-07-27 12:09:14,702][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:15,713][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:15,720][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:16,729][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:16,736][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:17,745][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:17,751][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:18,760][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:18,768][ERROR][1411]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:18,773][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:18,778][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:19,788][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:19,795][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:20,785][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:20,791][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:21,798][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:21,803][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:22,811][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:22,817][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:23,682][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:23,826][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:23,833][ERROR][1411]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:23,833][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:23,837][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:24,843][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:24,849][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:25,857][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:25,865][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:26,875][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:26,881][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:27,890][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:27,896][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:28,908][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:28,916][ERROR][1411]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:28,917][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:28,921][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:29,933][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:29,938][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:30,947][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:30,953][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:31,962][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:31,969][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:32,979][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:32,985][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:33,993][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:34,010][ERROR][1411]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:34,021][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:34,060][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:35,069][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:35,076][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:36,084][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:36,090][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:37,097][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:37,104][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:38,114][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:38,119][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:39,127][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:39,135][ERROR][1411]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:39,136][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:09:39,139][INFO][1411]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:09:40,147][ERROR][1411]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:09:40,154][WARNING][1411]: cannot find naming of polaris
[2021-07-27 12:10:17,542][WARNING][1423]: start backup threading
[2021-07-27 12:10:17,544][WARNING][1423]: start backup threading
[2021-07-27 12:10:17,544][INFO][1423]: success to start polaris engine
[2021-07-27 12:10:17,555][WARNING][1423]: start timing update job
[2021-07-27 12:10:17,556][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Production', 'service': '1961537:212729856', 'is_internal_request': False}
[2021-07-27 12:10:17,560][WARNING][1423]: start circuit break job
[2021-07-27 12:10:17,564][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:17,567][WARNING][1423]: start od job
[2021-07-27 12:10:17,572][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:17,575][WARNING][1423]: start job of client reporting
[2021-07-27 12:10:18,585][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:18,589][ERROR][1423]: receive exception when add client report task Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 26, in tcp_round_trip
    rsp = await asyncio.wait_for(options.checker.read_frame(conn), get_remain_time(ctx.deadline))
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 139, in report_client
    report_rsp = await proxy.report_client(req_proto, ctx, opts)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpcapi_pb2_trpc.py", line 41, in report_client
    return await self.client.invoke(ctx, request, rsp_cls, options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 287, in invoke
    raise err
  File "/usr/local/lib/python3.6/dist-packages/trpc/filter.py", line 97, in handle
    rsp = await asyncio.wait_for(func(ctx, req_obj), wait_for_time)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/dist-packages/trpc/client/client.py", line 325, in func
    rsp_buff = await client_ts.round_trip(ctx, req_buff, opts.call_options)
  File "/usr/local/lib/python3.6/dist-packages/trpc/transport/client_transport_tcp.py", line 32, in tcp_round_trip
    "client reached deadline to %s, %s io error " % (options.address, repr(e)))
trpc.exceptions.ClientTimeoutError: client reached deadline to ('9.136.125.12', 8091), TimeoutError() io error . timeout reason: ClientTimeoutReason.DownstreamTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 643, in add_client_report_task
    await self.do_period_client_report(values)
  File "/usr/local/lib/python3.6/dist-packages/polaris/pkg/flow/impl.py", line 669, in do_period_client_report
    report_client_resp = await self.svc_connector.report_client(report_client_req)
  File "/usr/local/lib/python3.6/dist-packages/polaris/plugin/serverconnector/trpc_connector/trpc_client.py", line 141, in report_client
    raise SDKError(ErrorCode.ErrCodeNetworkError, "fail to call report_client %s" % repr(e))
polaris.pkg.model.error.SDKError: (1007, 'fail to call report_client ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')

[2021-07-27 12:10:18,593][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:19,606][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:19,612][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:20,602][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:20,607][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:21,615][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:21,620][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:22,627][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:22,632][ERROR][1423]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:22,636][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:22,640][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:23,650][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:23,656][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:24,665][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:24,672][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:25,681][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.229\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:25,687][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:26,697][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:26,702][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:27,570][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:27,711][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:27,718][ERROR][1423]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:27,720][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:27,725][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:28,732][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:28,736][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:29,746][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:29,753][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:30,761][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:30,767][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:31,778][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:31,784][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:32,789][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:32,795][ERROR][1423]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:32,797][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:32,800][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:33,808][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:33,815][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:34,825][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:34,833][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:35,841][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:35,846][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:36,853][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:36,857][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:37,866][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:37,872][ERROR][1423]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:37,873][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:37,877][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:38,885][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.240\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:38,890][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:39,899][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:39,905][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:40,913][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:40,918][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:41,928][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:41,934][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:42,942][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:42,948][ERROR][1423]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.124.80\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:42,949][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:42,952][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:43,961][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:43,967][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:44,978][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:44,983][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:45,992][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:45,996][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:47,007][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.121.211\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:47,013][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:48,025][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:48,033][ERROR][1423]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:48,034][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:48,038][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:49,049][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:49,054][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:50,042][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.136.125.12\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:50,049][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:51,059][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:51,066][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:52,075][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:52,081][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:53,088][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:53,095][ERROR][1423]: Failed to discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} in periodic updating task because SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:53,096][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:53,099][INFO][1423]: miss local cache and begin to load remote value for {'namespace': 'Polaris', 'service': 'polaris.discover', 'is_internal_request': False}
[2021-07-27 12:10:54,110][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.121\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:54,117][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:55,127][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.8\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:55,131][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:56,139][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.125\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:56,145][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:57,153][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.27\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:57,160][WARNING][1423]: cannot find naming of polaris
[2021-07-27 12:10:58,168][ERROR][1423]: Failed to do discover {'namespace': 'Polaris', 'service': 'polaris.discover', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:58,175][ERROR][1423]: Failed to do discover {'namespace': 'Production', 'service': '1961537:212729856', 'event_type': 8193} and retry: SDKError(1007, 'Fail to call discover polaris.discover ClientTimeoutError("client reached deadline to (\'9.141.66.84\', 8091), TimeoutError() io error ",)')
[2021-07-27 12:10:58,176][WARNING][1423]: cannot find naming of polaris
